FROM budibase.docker.scarf.sh/budibase/apps
COPY ./patches/dist/templates.js /app/dist/api/controllers/templates.js
COPY ./patches/src/templates.js /app/src/api/controllers/templates.js
COPY ./SECURITY.txt /SECURITY.txt
